using System;

namespace FileGlitcher.Processors.ByteProviders
{
  /// <summary>
  /// Provides random generated bytes.
  /// </summary>
  public class RandomByteProvider : IByteProvider
  {
    #region Properties

    /// <summary>
    /// Seed for random number generation.
    /// </summary>
    public int Seed
    {
      get => _seed;
      set
      {
        if(Seed != value)
        {
          _seed = value;
          _rnd = new Random(Seed);
        }
      }
    }
    private int _seed;

    /// <summary>
    /// Minimum byte value to generate.
    /// </summary>
    public byte MinByte
    {
      get { return _minByte; }
      set
      {
        if (value > MaxByte)
          throw new ArgumentOutOfRangeException(nameof(MinByte));
        _minByte = value;
      }
    }
    private byte _minByte;

    /// <summary>
    /// Maximum byte value to generate.
    /// </summary>
    public byte MaxByte
    {
      get { return _maxByte; }
      set
      {
        if (value < MinByte)
          throw new ArgumentOutOfRangeException(nameof(MaxByte));
        _maxByte = value;
      }
    }
    private byte _maxByte;

    #endregion Properties

    #region Member

    private Random _rnd;

    #endregion Member

    #region Construction

    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="seed">Seed for random number generation.</param>
    /// <param name="minByte">Minimum byte value to generate.</param>
    /// <param name="maxByte">Maximum byte value to generate.</param>
    public RandomByteProvider(int seed, byte minByte, byte maxByte)
    {
      Seed = seed;
      MinByte = minByte;
      MaxByte = maxByte;
    }

    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="minByte">Minimum byte value to generate.</param>
    /// <param name="maxByte">Maximum byte value to generate.</param>
    public RandomByteProvider(byte minByte, byte maxByte)
      : this(DateTime.Now.Ticks.GetHashCode(), minByte, maxByte)
    { }

    /// <summary>
    /// Constructor.
    /// </summary>
    public RandomByteProvider()
      : this(0, 255)
    { }

    #endregion Construction

    /// <summary>
    /// Generates a random byte.
    /// </summary>
    /// <returns>Random generated byte.</returns>
    public byte GetByte()
    {
      return (byte)_rnd.Next(MinByte, MaxByte);
    }
  }
}