using System;

namespace FileGlitcher.Processors.ByteProviders
{
  /// <summary>
  /// Provides random generated bytes.
  /// </summary>
  public class RandomByteProvider : IByteProvider
  {
    #region Properties

    /// <summary>
    /// Generator for random numbers.
    /// </summary>
    public IRandomNumberGenerator RandomNumberGenerator;

    /// <summary>
    /// Minimum byte value to generate.
    /// </summary>
    public byte MinByte
    {
      get { return _minByte; }
      set
      {
        if (value > MaxByte)
          throw new ArgumentOutOfRangeException(nameof(MinByte));
        _minByte = value;
      }
    }
    private byte _minByte;

    /// <summary>
    /// Maximum byte value to generate.
    /// </summary>
    public byte MaxByte
    {
      get { return _maxByte; }
      set
      {
        if (value < MinByte)
          throw new ArgumentOutOfRangeException(nameof(MaxByte));
        _maxByte = value;
      }
    }
    private byte _maxByte;

    #endregion Properties

    #region Construction

    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="randomNumberGenerator">Generator for random numbers.</param>
    /// <param name="minByte">Minimum byte value to generate.</param>
    /// <param name="maxByte">Maximum byte value to generate.</param>
    public RandomByteProvider(IRandomNumberGenerator randomNumberGenerator, byte minByte, byte maxByte)
    {
      RandomNumberGenerator = randomNumberGenerator ?? throw new ArgumentNullException(nameof(randomNumberGenerator));
      MinByte = minByte;
      MaxByte = maxByte;
    }

    /// <summary>
    /// Constructor.
    /// </summary>
    /// <param name="minByte">Minimum byte value to generate.</param>
    /// <param name="maxByte">Maximum byte value to generate.</param>
    public RandomByteProvider(byte minByte, byte maxByte)
      : this(new RandomNumberGenerator(), minByte, maxByte)
    { }

    #endregion Construction

    /// <summary>
    /// Generates a random byte.
    /// </summary>
    /// <returns>Random generated byte.</returns>
    public byte GetByte()
    {
      return (byte)RandomNumberGenerator.GetRandomNumber(MinByte, MaxByte);
    }
  }
}